# permissions for end users to edit iplookups.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: iplookup-editor-role
rules:
- apiGroups:
  - networking.thehomelab.tech
  resources:
  - iplookups
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - networking.thehomelab.tech
  resources:
  - iplookups/status
  verbs:
  - get
