# permissions for end users to view iplookups.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: iplookup-viewer-role
rules:
- apiGroups:
  - networking.thehomelab.tech
  resources:
  - iplookups
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - networking.thehomelab.tech
  resources:
  - iplookups/status
  verbs:
  - get
